//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cff.SaferTrader.Web.UserControls.ReleaseTabs {
    
    
    public partial class ScheduleTab {
        
        /// <summary>
        /// managementDetailsBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cff.SaferTrader.Web.UserControls.ManagementDetailsBox managementDetailsBox;
        
        /// <summary>
        /// batchSchedulePanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cff.SaferTrader.Web.UserControls.ReleaseTabs.BatchSchedulePanel batchSchedulePanel;
    }
}
