//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cff.SaferTrader.Web.Popups {
    
    
    public partial class InvoiceBatchNonFactoredInvoicesPopup {
        
        /// <summary>
        /// header control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cff.SaferTrader.Web.UserControls.ReleaseTabs.InvoiceBatchHeader header;
        
        /// <summary>
        /// CffGGV_InvoiceGridView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cff.SaferTrader.Web.UserControls.gGridViewControls.CffGenGridView CffGGV_InvoiceGridView;
        
        /// <summary>
        /// DatePrintedLiteral control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal DatePrintedLiteral;
        
        /// <summary>
        /// YearLiteral control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal YearLiteral;
    }
}
