//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cff.SaferTrader.Web.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Cff_WebResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Cff_WebResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cff.SaferTrader.Web.App_GlobalResources.Cff_WebResource", typeof(Cff_WebResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow calls:.
        /// </summary>
        internal static string allowcallsLabel {
            get {
                return ResourceManager.GetString("allowcallsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/images/sr_arrow_down.png.
        /// </summary>
        internal static string ArrowDownImage {
            get {
                return ResourceManager.GetString("ArrowDownImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/images/sr_arrow_up.png.
        /// </summary>
        internal static string ArrowUpImage {
            get {
                return ResourceManager.GetString("ArrowUpImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to view batch details.
        /// </summary>
        internal static string batchNumberLinkTooltip {
            get {
                return ResourceManager.GetString("batchNumberLinkTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to load client&apos;s Dashboard.
        /// </summary>
        internal static string clientNameLinkTooltip {
            get {
                return ResourceManager.GetString("clientNameLinkTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passkey is invalid. Please verify your organization passkey from your Manager..
        /// </summary>
        internal static string CreateUserFailPasskeyError {
            get {
                return ResourceManager.GetString("CreateUserFailPasskeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit limit:.
        /// </summary>
        internal static string creditLimitLabel {
            get {
                return ResourceManager.GetString("creditLimitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to load customer&apos;s Dashboard.
        /// </summary>
        internal static string customerNameLinkTooltip {
            get {
                return ResourceManager.GetString("customerNameLinkTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GST:.
        /// </summary>
        internal static string InvoiceBatchesScheduleAdminFeeGstLabel {
            get {
                return ResourceManager.GetString("InvoiceBatchesScheduleAdminFeeGstLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Fee:.
        /// </summary>
        internal static string InvoiceBatchesScheduleAdminFeeLabel {
            get {
                return ResourceManager.GetString("InvoiceBatchesScheduleAdminFeeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Fee Total:.
        /// </summary>
        internal static string InvoiceBatchesScheduleAdminFeeTotalLabel {
            get {
                return ResourceManager.GetString("InvoiceBatchesScheduleAdminFeeTotalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available for Release:.
        /// </summary>
        internal static string InvoiceBatchesScheduleAvailableForReleaseLabel {
            get {
                return ResourceManager.GetString("InvoiceBatchesScheduleAvailableForReleaseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note:.
        /// </summary>
        internal static string InvoiceBatchesScheduleBatchNoteLabel {
            get {
                return ResourceManager.GetString("InvoiceBatchesScheduleBatchNoteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment/Charges:.
        /// </summary>
        internal static string InvoiceBatchesScheduleChargesTotalLabel {
            get {
                return ResourceManager.GetString("InvoiceBatchesScheduleChargesTotalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To be Checked or Confirmed:.
        /// </summary>
        internal static string InvoiceBatchesScheduleCheckConfirmLabel {
            get {
                return ResourceManager.GetString("InvoiceBatchesScheduleCheckConfirmLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits:.
        /// </summary>
        internal static string InvoiceBatchesScheduleCreditLabel {
            get {
                return ResourceManager.GetString("InvoiceBatchesScheduleCreditLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Date:.
        /// </summary>
        internal static string InvoiceBatchesScheduleDateFinishedLabel {
            get {
                return ResourceManager.GetString("InvoiceBatchesScheduleDateFinishedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deductions:.
        /// </summary>
        internal static string InvoiceBatchesScheduleDeductionsLabel {
            get {
                return ResourceManager.GetString("InvoiceBatchesScheduleDeductionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices Factored:.
        /// </summary>
        internal static string InvoiceBatchesScheduleFactoredLabel {
            get {
                return ResourceManager.GetString("InvoiceBatchesScheduleFactoredLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factor Fee:.
        /// </summary>
        internal static string InvoiceBatchesScheduleFactorFeeLabel {
            get {
                return ResourceManager.GetString("InvoiceBatchesScheduleFactorFeeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non Factored Invoices:.
        /// </summary>
        internal static string InvoiceBatchesScheduleNonFactoredInvoicesLabel {
            get {
                return ResourceManager.GetString("InvoiceBatchesScheduleNonFactoredInvoicesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postage:.
        /// </summary>
        internal static string InvoiceBatchesSchedulePostageLabel {
            get {
                return ResourceManager.GetString("InvoiceBatchesSchedulePostageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postage Total:.
        /// </summary>
        internal static string InvoiceBatchesSchedulePostageTotalLabel {
            get {
                return ResourceManager.GetString("InvoiceBatchesSchedulePostageTotalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GST:.
        /// </summary>
        internal static string InvoiceBatchesSchedulePostGstLabel {
            get {
                return ResourceManager.GetString("InvoiceBatchesSchedulePostGstLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date:.
        /// </summary>
        internal static string InvoiceBatchesScheduleReleasedLabel {
            get {
                return ResourceManager.GetString("InvoiceBatchesScheduleReleasedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repurchases:.
        /// </summary>
        internal static string InvoiceBatchesScheduleRepurchasesLabel {
            get {
                return ResourceManager.GetString("InvoiceBatchesScheduleRepurchasesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retention Held:.
        /// </summary>
        internal static string InvoiceBatchesScheduleRetentionHeldLabel {
            get {
                return ResourceManager.GetString("InvoiceBatchesScheduleRetentionHeldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        internal static string InvoiceBatchesScheduleStatusDescriptionLabel {
            get {
                return ResourceManager.GetString("InvoiceBatchesScheduleStatusDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Invoices:.
        /// </summary>
        internal static string InvoiceBatchesScheduleTotalInvoiceLabel {
            get {
                return ResourceManager.GetString("InvoiceBatchesScheduleTotalInvoiceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last amount:.
        /// </summary>
        internal static string lastAmountLabel {
            get {
                return ResourceManager.GetString("lastAmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last paid:.
        /// </summary>
        internal static string lastPaidLabel {
            get {
                return ResourceManager.GetString("lastPaidLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List date:.
        /// </summary>
        internal static string listDateLabel {
            get {
                return ResourceManager.GetString("listDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your username or password was incorrect, please try again..
        /// </summary>
        internal static string LogOnFail {
            get {
                return ResourceManager.GetString("LogOnFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is not yet approved by the administrator..
        /// </summary>
        internal static string LogOnFailApprovalNeeded {
            get {
                return ResourceManager.GetString("LogOnFailApprovalNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password was incorrect, please try again..
        /// </summary>
        internal static string LogOnFailIncorrectPassword {
            get {
                return ResourceManager.GetString("LogOnFailIncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been locked out, please contact your site administrator..
        /// </summary>
        internal static string LogOnFailLockedOut {
            get {
                return ResourceManager.GetString("LogOnFailLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no user with the user name;.
        /// </summary>
        internal static string LogOnFailNoUser {
            get {
                return ResourceManager.GetString("LogOnFailNoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your access are now activated and no longer require an approval from company registrant..
        /// </summary>
        internal static string msgEmailApprovalNotNeeded {
            get {
                return ResourceManager.GetString("msgEmailApprovalNotNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We already sent an email to your company registrant for CFF Client Portal access. You will receive an email from us for the status of your access request.&lt;br/&gt;&lt;br/&gt;Thank you for your patience.&lt;br/&gt;&lt;/br&gt;.
        /// </summary>
        internal static string msgEmailApprovalSent {
            get {
                return ResourceManager.GetString("msgEmailApprovalSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email has been verified already in our system..
        /// </summary>
        internal static string msgVerificationDup {
            get {
                return ResourceManager.GetString("msgVerificationDup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The verification link is invalid. Please register again..
        /// </summary>
        internal static string msgVerificationInvalid {
            get {
                return ResourceManager.GetString("msgVerificationInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next call:.
        /// </summary>
        internal static string nextCallLabel {
            get {
                return ResourceManager.GetString("nextCallLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password you entered are not matched..
        /// </summary>
        internal static string PasswordMismatched {
            get {
                return ResourceManager.GetString("PasswordMismatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop credit:.
        /// </summary>
        internal static string stopCreditLabel {
            get {
                return ResourceManager.GetString("stopCreditLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email verification Error.
        /// </summary>
        internal static string titleVerificationError {
            get {
                return ResourceManager.GetString("titleVerificationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email verification Successful.
        /// </summary>
        internal static string titleVerificationSuccessful {
            get {
                return ResourceManager.GetString("titleVerificationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry your search has timed out, please try again..
        /// </summary>
        internal static string transacionSearchTimeOutMessage {
            get {
                return ResourceManager.GetString("transacionSearchTimeOutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all records.
        /// </summary>
        internal static string viewAllRecordsText {
            get {
                return ResourceManager.GetString("viewAllRecordsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View pages.
        /// </summary>
        internal static string viewPagesText {
            get {
                return ResourceManager.GetString("viewPagesText", resourceCulture);
            }
        }
    }
}
